# Generated by Django 4.1.6 on 2023-03-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_link',
            field=models.URLField(blank=True),
        ),
    ]
