# Generated by Django 4.1.6 on 2023-03-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overview',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
